// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGnyrgotXrID8rIMGsNabxnxdjZYRe1OQ',
    appId: '1:363345592670:web:602fa57b397dcad6db0fcf',
    messagingSenderId: '363345592670',
    projectId: 'book-room-23184',
    authDomain: 'book-room-23184.firebaseapp.com',
    storageBucket: 'book-room-23184.firebasestorage.app',
    measurementId: 'G-8N2EPTVPKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOLVsIDxD1mgL7iwV1SkZnGt3R4fs9As',
    appId: '1:363345592670:android:bc1489fd6c6c8380db0fcf',
    messagingSenderId: '363345592670',
    projectId: 'book-room-23184',
    storageBucket: 'book-room-23184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqVXCQrd8JuYrVucRdwN1L5K6r9NtF9Q',
    appId: '1:363345592670:ios:d47ab577afeaac7bdb0fcf',
    messagingSenderId: '363345592670',
    projectId: 'book-room-23184',
    storageBucket: 'book-room-23184.firebasestorage.app',
    iosBundleId: 'com.example.bookroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqVXCQrd8JuYrVucRdwN1L5K6r9NtF9Q',
    appId: '1:363345592670:ios:d47ab577afeaac7bdb0fcf',
    messagingSenderId: '363345592670',
    projectId: 'book-room-23184',
    storageBucket: 'book-room-23184.firebasestorage.app',
    iosBundleId: 'com.example.bookroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGnyrgotXrID8rIMGsNabxnxdjZYRe1OQ',
    appId: '1:363345592670:web:62fd0c2758df89c7db0fcf',
    messagingSenderId: '363345592670',
    projectId: 'book-room-23184',
    authDomain: 'book-room-23184.firebaseapp.com',
    storageBucket: 'book-room-23184.firebasestorage.app',
    measurementId: 'G-EYLW1RDTGR',
  );

}